# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9f100bfd44717437eb251a438e56befe60b2f44dde7177965a4f628aee05ac59409100721d5fbab0f4fd1596fb151546370ab31376e1d1562288015c0f73ba

test:
  secret_key_base: 99602ed1b812d7187693797d5a763a48d00311578c6819ad767df20fd313f444391a2e577f824ce90dc313568a17dda95cdf5fd7bdb6927646d9fd1699c9ab54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
